version: '3.9'

services:

  mongo:
    image: mongo:6
    container_name: visionvoice-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - visionvoice-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: visionvoice-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      LANGCHAIN_TRACING: "true"
      LANGCHAIN_ENDPOINT: "https://api.smith.langchain.com"
      DB_URI: "mongodb://mongo:27017/visionvoiceDB"
    depends_on:
      - mongo
    networks:
      - visionvoice-net
    volumes:
      - ./backend/app:/app/app

networks:
  visionvoice-net:
    driver: bridge

volumes:
  mongo_data: