services:

  mongo:
    image: mongo:6
    container_name: visionvoice-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - visionvoice-net

volumes:
  mongo_data:

networks:
  visionvoice-net:
    driver: bridge
